server: # serveur addresse d'écoute eet port
  address: 0.0.0.0
  port: 8888
peer: # serveur addresse et port
  address: localhost
  port: 8887
files_list: "b.txt,a" # listes des fichiers servis par A
remote_files_list: "b.txt,a" # liste des fichiers partagés avec B
